#!/bin/bash

rm -r AvOPs

cp $1 INPUT.pdb

Fname=$(grep "FrameworkName" sites.input | awk '{print $2}')

grep "ATOM" $1 | awk '{print $5,$6,$7}' > atom-positions.dat
grep "ATOM" ${Fname}_Framework_sites.pdb | awk '{print $5,$6,$7}' > SITE-positions.dat

wc -l INPUT.pdb | awk '{print $1}' > input-fortran
grep MODEL INPUT.pdb | wc -l >> input-fortran
wc -l atom-positions.dat | awk '{print $1}' >> input-fortran
grep "CRYST" INPUT.pdb | head -1 | awk '{print $2,$3,$4,$5,$6,$7}' >> input-fortran
grep -v "#" sites.input >> input-fortran 

mkdir AvOPs

mkdir AvOPs/1D
mkdir AvOPs/2D

/home/vicent/Dropbox/Raspa/delfin/SITES-Analyzer/SITES-ANALYZER/execute/site.x
  
cp /home/vicent/Dropbox/Raspa/delfin/SITES-Analyzer/SITES-ANALYZER/gnuplot-script/plot-AvOPs-2D.gnuplot AvOPs/2D/.
cd AvOPs/2D
gnuplot plot-AvOPs-2D.gnuplot
cd ../../

rm atom-positions.dat SITE-positions.dat
rm input-fortran INPUT.pdb

echo "      "
echo "       =============    "
echo "       End Of Script    "
echo "       =============    "
echo "      "
